language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - nightly

cache: cargo

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then which rustfmt || cargo install rustfmt-nightly; fi;

script:
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo fmt -- --write-mode=diff; fi;
  - cargo build
  - cargo test
