[package]
name = "nom-bibtex"
version = "0.2.0"
authors = ["Charles Vandevoorde <charles.vandevoorde@hotmail.be>"]

description = "BibTeX parser using nom"
categories = ["parsing"]
keywords = ["bibtex", "latex", "parser", "nom"]

repository = "https://github.com/charlesvdv/nom-bibtex"
documentation = "https://docs.rs/nom-bibtex"

edition="2018"

license = "MIT"

[lib]
name = "nom_bibtex"

[badges]
travis-ci = { repository = "charlesvdv/nom-bibtex" }

[dependencies]
nom = "5.1.0"
quick-error = "1.2.*"
nom-tracable = "0.5.2"
nom_locate = "2.0.0"

[features]
default = []
trace = ["nom-tracable/trace"]
